# 📊 Exploratory Data Analysis (EDA)

## 🛍️ Project Title
**Amazon Product Sales - Exploratory Data Analysis**

---

## 🎯 Objective
The objective of this project is to explore the cleaned Amazon product sales dataset to uncover meaningful patterns, trends, and insights. This analysis aims to understand product pricing, customer ratings, reviews, discounts, product categories and delivery trends through statistical summaries and visualizations. The findings can help identify factors that influence product popularity and sales performance.

---

## 📁 Dataset Description
The dataset contains cleaned information about Amazon products collected from an e-commerce platform. It includes product details, pricing, discounts, customer ratings, reviews, product categories, delivery details, and other relevant attributes.

### Key Features
- Product Name
- Main Category
- Rating
- Review count
- Unit sold
- Discounted Price
- Original Price
- ***Discount Percentage****
- Best seller
- Delivery Date
- Delivery Day
- Delivery Month
- And other cleaned product-related attributes

The dataset has already undergone data cleaning and preprocessing to handle missing values, inconsistent formats, duplicate records, and incorrect data types.

---

## ❓ Questions to Answer

### Product Analysis
- Which product categories contain the highest number of products?
- What are the most common product categories?

### Pricing Analysis
- What is the distribution of discounted prices?
- Which categories have the highest average discounted price?
- Which products receive the highest discounts?
- Is there a relationship between original price and discounted price?

### Rating & Review Analysis
- How are product ratings distributed?
- Which categories have the highest average ratings?
- Which products have the largest number of ratings and reviews?
- Do highly rated products receive more reviews?

### Discount Analysis
- Which categories offer the highest discounts?
- Is there a relationship between discount percentage and product ratings?
- Do larger discounts lead to more customer reviews?

### Delivery Analysis
- Which delivery day occurs most frequently?
- Are products delivered more often in specific months?

### Correlation Analysis
- Is there a relationship between price and rating?
- Does review count increase with rating count?
- Which numerical features are strongly correlated?

### Overall Insights
- What are the key trends and patterns in the dataset?
- What business insights can be derived from the analysis?
- What recommendations can improve product performance and customer engagement?

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Loading Clean Dataset
df = pd.read_csv('C:/Users/Admin/DataScienceCourse/Amazon_Project/data/Interim/amazon_product_sales_cleaned.csv')

In [3]:
# changing datatype
df['delivery_date'] = pd.to_datetime(df['delivery_date'])
df['data_collected_at'] = pd.to_datetime(df['data_collected_at'])

In [4]:
# overview
df.head()

,product_title,product_category,product_rating,review_count,units_sold_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_couponed,buy_box_availability,delivery_date,delivery_month,delivery_day,image_url,product_url,data_collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,Smartphones,4.6,375,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,September,Monday,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",Smartphones,4.3,2457,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,August,Friday,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",Smartphones,4.6,3044,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,September,Monday,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",Headphones & Earbuds,4.6,35882,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,Not Available,NaT,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,Smartphones,4.8,28988,10000.0,72.74,72.74,No Badge,Organic,No Coupon,Not Available,NaT,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29

## Dataset Overview

In [5]:
# Shape
df.shape

(40135, 17)

In [6]:
# columns
df.columns

Index(['product_title', 'product_category', 'product_rating', 'review_count',
       'units_sold_last_month', 'discounted_price', 'original_price',
       'is_best_seller', 'is_sponsored', 'has_couponed',
       'buy_box_availability', 'delivery_date', 'delivery_month',
       'delivery_day', 'image_url', 'product_url', 'data_collected_at'],
      dtype='object')

In [7]:
# Datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40135 entries, 0 to 40134
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_title          40135 non-null  object
 1   product_category       40135 non-null  object
 2   product_rating         39118 non-null  float64
 3   review_count           40135 non-null  int64
 4   units_sold_last_month  30357 non-null  float64
 5   discounted_price       39993 non-null  float64
 6   original_price         39993 non-null  float64
 7   is_best_seller         40135 non-null  object
 8   is_sponsored           40135 non-null  object
 9   has_couponed           40135 non-null  object
 10  buy_box_availability   40135 non-null  object
 11  delivery_date          30692 non-null  datetime64[ns]
 12  delivery_month         30692 non-null  object
 13  delivery_day           30692 non-null  object
 14  image_url              40135 non-null  object
 15  product_url            38131 non-null  object
 16  data_collected_at      40135 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(4), int64(1), object(10)
memory usage: 5.2+ MB

In [8]:
# Missing Values
df.isnull().sum()

product_title               0
product_category            0
product_rating           1017
review_count                0
units_sold_last_month    9778
discounted_price          142
original_price            142
is_best_seller              0
is_sponsored                0
has_couponed                0
buy_box_availability        0
delivery_date            9443
delivery_month           9443
delivery_day             9443
image_url                   0
product_url              2004
data_collected_at           0
dtype: int64

In [9]:
# Duplicated rows
df.duplicated().sum()

np.int64(0)

In [10]:
# summary statistics
df.describe()

,product_rating,review_count,units_sold_last_month,discounted_price,original_price,delivery_date,data_collected_at
count,39118.000000,40135.000000,30357.000000,39993.000000,39993.000000,30692,40135
mean,4.408899,2959.789710,1350.085647,207.981149,222.587955,2025-09-04 06:42:02.298970368,2025-08-26 11:31:20.296100864
min,1.000000,0.000000,50.000000,2.160000,2.160000,2025-08-27 00:00:00,2025-08-21 11:14:29
25%,4.200000,76.000000,100.000000,28.990000,30.990000,2025-09-02 00:00:00,2025-08-24 21:56:14
50%,4.500000,336.000000,200.000000,79.990000,85.990000,2025-09-03 00:00:00,2025-08-25 11:26:46
75%,4.700000,1845.000000,400.000000,216.660000,219.000000,2025-09-04 00:00:00,2025-08-29 11:21:10
max,5.000000,865598.000000,100000.000000,4699.000000,5399.000000,2025-09-29 00:00:00,2025-08-30 19:56:33
std,0.383922,13058.868528,6463.762206,356.690530,388.828782,NaN,NaN